global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Text;
global using System.Threading.Tasks;
global using Core.Entities;
global using Core.Specifications;
global using Core.Interfaces;
